### ISSUE TITLE
Debian GNU/Linux packaging

### ISSUE THREAD

**Issue by dachary** [signalapp/libsignal-service-java#50]
Dear Signal maintainers,

I [intend to package libsignal-service-java for Debian GNU/Linux](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890915) and it would be great if you could let me know how you feel about it. Quoting the [maintainer guide](https://www.debian.org/doc/manuals/maint-guide/first.en.html):

> You should contact the program's author(s) to check if they agree with packaging it and are amicable to Debian. It is important to be able to consult with the author(s) in case of any problems with the program, so don't try to package unmaintained software. 

Please kindly let me know what you think and thanks for a great piece of software !

**Comment by moxie0** [comment]
Hey @dachary, thanks for your interest, but I'd prefer it if you didn't. This is designed to be "evergreen" software consumed as a maven artifact. Distributing it through another channel would only complicate things without providing any clear benefit. Thanks though.

**Comment by leo-bogert** [comment]
@moxie0 
> Hey @dachary, thanks for your interest, but I'd prefer it if you didn't. This is designed to be "evergreen" software consumed as a maven artifact. Distributing it through another channel would only complicate things without providing any clear benefit. Thanks though.

Hmm I never heard of "evergreen software". Can you please clarify what you mean by that and what the benefit of it is supposed to be which is worth restricting on how users can deploy it to their operating systems?

FYI the benefits of getting Signal available as a package in Debian's official repositories IMHO are:
- for users: that they don't have to give you root to their system by adding your package repositories. They  would only have to trust the distribution maintainers, which they already have to do anyway.
- for you and the rest of the Signal team: you become less likely to be a target of hacks or even blackmail for someone who wants to root many systems.

The less people who can root a system the better.

**Comment by Trolldemorted** [comment]
>for users: that they don't have to give you root to their system by adding your package repositories. They would only have to trust the distribution maintainers, which they already have to do anyway.

The signal team does not operate any package repositories, so no one gives them root.

**Comment by leo-bogert** [comment]
@Trolldemorted 
> The signal team does not operate any package repositories, so no one gives them root.

No, Signal Desktop requires using a repository of theirs: https://signal.org/download/
See the instructions for Debian-based Linux. They tell you to add the repository `https://updates.signal.org/desktop/apt` to your apt.
There's no tarball either.

**Comment by Trolldemorted** [comment]
Signal-Desktop's deployment has absolutely nothing to do with Signal-Android or libsignal-service-java.

**Comment by Trolldemorted** [comment]
Signal-Desktop was a chrome app and I think it was not possible to use native libs (or managed ones) on that platform, so Signal-Desktop uses a javascript implementation of the libsignal stack.

Why would you ever install a non-system library with a package manager? libsignal-service-java is supposed to be shipped with any app that uses it, in Signal-Android's case it is packaged into the android package kit. If you want to build an app that depends on libsignal-service-java you specify a version, let gradle [verify the hashsum](https://github.com/signalapp/Signal-Android/blob/master/build.gradle#L177), and that's it.

Letting others maintain a package for your app (like Signal-Desktop) is bad because you are [no longer in control which version is shipped, and users blame and annoy you for bugs you fixed ages ago](https://www.jwz.org/blog/2016/04/i-would-like-debian-to-stop-shipping-xscreensaver/).

**Comment by Chris56** [comment]
Package maintainers do a really good job. It is very strange, that thousands of other packages are happy about and appreciate the valuable and quality assuring work of people that know their respective distribution by heart.  I can only guess that there is a hidden agenda being hostile towards this support.

Signals download website says:
Signal for Debian-based Linux
This is wrong (see https://github.com/signalapp/Signal-Desktop/issues/2604)!
Change this to:
Debian package manager package (which may or may not work on your distro)

Debian jessie is - I presume - debian based. It's long term support lasts till June 2020!!!
But the package your provide does not work at all on debian jessie.
It was reported and has been known for months (and also the reason for the bug has been analysed and provided!!), but signal doesn't care and this exactly would not have happened with a proper package maintainer: it would have long been repaired by the maintainer!
I already know very many people that turned signal down because of this hostile behaviour.

**Comment by scarf** [comment]
Note that @moxie0 only "prefers" that you listen to him.  There's nothing really stopping us or package maintainers from doing what we want to make the software work how we want it to for ourselves or the users that depend on us.
